[switch]
ipaddress = "0.0.0.0"

[statistics]
# Order the output of statistics by numbering here. Use a 0 to exclude a statistic.
"Neutral Wins" = 1
"Stocks Taken" = 2
"Openings / Kill" = 3
"Neutral Win %" = 4
"Total Damage Dealt" = 5
"Average Kill Percent" = 6
"Average Damage / Opening" = 7
"Earliest Kill" = 8
"Latest Death" = 9
"Stage Control" = 10
